/* tslint:disable */
/* eslint-disable */
/**
 * GinSqlBlog
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  LoginReq,
  LoginRsp,
  SqlReq,
  SqlRsp,
} from '../models/index';
import {
    LoginReqFromJSON,
    LoginReqToJSON,
    LoginRspFromJSON,
    LoginRspToJSON,
    SqlReqFromJSON,
    SqlReqToJSON,
    SqlRspFromJSON,
    SqlRspToJSON,
} from '../models/index';

export interface UserLoginPostRequest {
    loginReq?: LoginReq;
}

export interface UserPostModifyPostRequest {
    sqlReq?: SqlReq;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * 
     * 用户登录接口
     */
    async userLoginPostRaw(requestParameters: UserLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LoginRsp>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/user/login`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LoginReqToJSON(requestParameters['loginReq']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LoginRspFromJSON(jsonValue));
    }

    /**
     * 
     * 用户登录接口
     */
    async userLoginPost(requestParameters: UserLoginPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LoginRsp> {
        const response = await this.userLoginPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * 用户报文接口
     */
    async userPostModifyPostRaw(requestParameters: UserPostModifyPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SqlRsp>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/user/postModify`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SqlReqToJSON(requestParameters['sqlReq']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SqlRspFromJSON(jsonValue));
    }

    /**
     * 
     * 用户报文接口
     */
    async userPostModifyPost(requestParameters: UserPostModifyPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SqlRsp> {
        const response = await this.userPostModifyPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
