/* tslint:disable */
/* eslint-disable */
/**
 * WutonkGinBlog
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  InfoResp,
  LoginReq,
  LoginResp,
} from '../models/index';
import {
    InfoRespFromJSON,
    InfoRespToJSON,
    LoginReqFromJSON,
    LoginReqToJSON,
    LoginRespFromJSON,
    LoginRespToJSON,
} from '../models/index';

export interface UserInfoGetRequest {
    authorization?: string;
}

export interface UserLoginPostRequest {
    loginReq?: LoginReq;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * 
     * 用户信息接口
     */
    async userInfoGetRaw(requestParameters: UserInfoGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InfoResp>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/user/info`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InfoRespFromJSON(jsonValue));
    }

    /**
     * 
     * 用户信息接口
     */
    async userInfoGet(requestParameters: UserInfoGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InfoResp> {
        const response = await this.userInfoGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * 用户登陆接口
     */
    async userLoginPostRaw(requestParameters: UserLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LoginResp>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/user/login`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LoginReqToJSON(requestParameters['loginReq']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LoginRespFromJSON(jsonValue));
    }

    /**
     * 
     * 用户登陆接口
     */
    async userLoginPost(requestParameters: UserLoginPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LoginResp> {
        const response = await this.userLoginPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
