/* tslint:disable */
/* eslint-disable */
/**
 * WutonkGinBlog
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InfoResp
 */
export interface InfoResp {
    /**
     * 
     * @type {string}
     * @memberof InfoResp
     */
    nickName: string;
}

/**
 * Check if a given object implements the InfoResp interface.
 */
export function instanceOfInfoResp(value: object): value is InfoResp {
    if (!('nickName' in value) || value['nickName'] === undefined) return false;
    return true;
}

export function InfoRespFromJSON(json: any): InfoResp {
    return InfoRespFromJSONTyped(json, false);
}

export function InfoRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): InfoResp {
    if (json == null) {
        return json;
    }
    return {
        
        'nickName': json['nick_name'],
    };
}

export function InfoRespToJSON(json: any): InfoResp {
    return InfoRespToJSONTyped(json, false);
}

export function InfoRespToJSONTyped(value?: InfoResp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nick_name': value['nickName'],
    };
}

