/* tslint:disable */
/* eslint-disable */
/**
 * WutonkGinBlog
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginResp
 */
export interface LoginResp {
    /**
     * 
     * @type {string}
     * @memberof LoginResp
     */
    token: string;
}

/**
 * Check if a given object implements the LoginResp interface.
 */
export function instanceOfLoginResp(value: object): value is LoginResp {
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function LoginRespFromJSON(json: any): LoginResp {
    return LoginRespFromJSONTyped(json, false);
}

export function LoginRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginResp {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
    };
}

export function LoginRespToJSON(json: any): LoginResp {
    return LoginRespToJSONTyped(json, false);
}

export function LoginRespToJSONTyped(value?: LoginResp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
    };
}

