/* tslint:disable */
/* eslint-disable */
/**
 * GinSqlBlog
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginRsp
 */
export interface LoginRsp {
    /**
     * 
     * @type {string}
     * @memberof LoginRsp
     */
    token: string;
}

/**
 * Check if a given object implements the LoginRsp interface.
 */
export function instanceOfLoginRsp(value: object): value is LoginRsp {
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function LoginRspFromJSON(json: any): LoginRsp {
    return LoginRspFromJSONTyped(json, false);
}

export function LoginRspFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginRsp {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
    };
}

export function LoginRspToJSON(json: any): LoginRsp {
    return LoginRspToJSONTyped(json, false);
}

export function LoginRspToJSONTyped(value?: LoginRsp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
    };
}

