/* tslint:disable */
/* eslint-disable */
/**
 * WutonkGinBlog
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginReq
 */
export interface LoginReq {
    /**
     * ID 编号
     * @type {string}
     * @memberof LoginReq
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof LoginReq
     */
    password: string;
}

/**
 * Check if a given object implements the LoginReq interface.
 */
export function instanceOfLoginReq(value: object): value is LoginReq {
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function LoginReqFromJSON(json: any): LoginReq {
    return LoginReqFromJSONTyped(json, false);
}

export function LoginReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginReq {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'],
        'password': json['password'],
    };
}

export function LoginReqToJSON(json: any): LoginReq {
    return LoginReqToJSONTyped(json, false);
}

export function LoginReqToJSONTyped(value?: LoginReq | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'password': value['password'],
    };
}

