/* tslint:disable */
/* eslint-disable */
/**
 * GinSqlBlog
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SqlReq
 */
export interface SqlReq {
    /**
     * 
     * @type {string}
     * @memberof SqlReq
     */
    mode: string;
    /**
     * 
     * @type {string}
     * @memberof SqlReq
     */
    token: string;
    /**
     * 
     * @type {string}
     * @memberof SqlReq
     */
    userName: string;
    /**
     * 
     * @type {string}
     * @memberof SqlReq
     */
    appendText: string;
}

/**
 * Check if a given object implements the SqlReq interface.
 */
export function instanceOfSqlReq(value: object): value is SqlReq {
    if (!('mode' in value) || value['mode'] === undefined) return false;
    if (!('token' in value) || value['token'] === undefined) return false;
    if (!('userName' in value) || value['userName'] === undefined) return false;
    if (!('appendText' in value) || value['appendText'] === undefined) return false;
    return true;
}

export function SqlReqFromJSON(json: any): SqlReq {
    return SqlReqFromJSONTyped(json, false);
}

export function SqlReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): SqlReq {
    if (json == null) {
        return json;
    }
    return {
        
        'mode': json['mode'],
        'token': json['token'],
        'userName': json['userName'],
        'appendText': json['appendText'],
    };
}

export function SqlReqToJSON(json: any): SqlReq {
    return SqlReqToJSONTyped(json, false);
}

export function SqlReqToJSONTyped(value?: SqlReq | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mode': value['mode'],
        'token': value['token'],
        'userName': value['userName'],
        'appendText': value['appendText'],
    };
}

