/*
 * GinSqlBlog
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type SqlReq struct {

	Mode string `json:"mode"`

	Token string `json:"token"`

	UserName string `json:"userName"`

	AppendText string `json:"appendText"`
}
