/*
 * GinSqlBlog
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type LoginReq struct {

	Username string `json:"username"`

	Password string `json:"password"`
}
